Output vhs/gifs/runImage.gif

Require gmd

Set FontSize 16
Set Width 1920
Set Height 1080
Set TypingSpeed 0.1
Set Theme Batman
Set Shell zsh

Sleep 500ms
Type "gmd"
Enter
Sleep 2s
Type "l"
Sleep 2s
Type "h"
Sleep 500ms
Type@500ms "jjjj"
Sleep 1s
Type "r"
Sleep 1s
Type@150ms "80:80, 34000:35000"
Enter
Type@150ms "reeeeedis"
Enter
Type@150ms "USER=me,PASSWORD=pass"
Enter
Sleep 2s
Type "l"
Sleep 3s
Type "q"

